version: '3.1'

services:
  IVL:
    build: ./ivl
    ports:
      - 8081:80

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1